# Generated by Django 4.2.4 on 2024-01-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.SmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('pokedex_no_field', models.SmallIntegerField(blank=True, db_column='Pokedex No.', null=True)),
                ('name', models.CharField(db_column='Name')),
                ('type_1', models.CharField(db_column='Type 1')),
                ('type_2', models.CharField(blank=True, db_column='Type 2', null=True)),
                ('total', models.SmallIntegerField(db_column='Total')),
                ('hp', models.SmallIntegerField(db_column='HP')),
                ('attack', models.SmallIntegerField(db_column='Attack')),
                ('defense', models.SmallIntegerField(db_column='Defense')),
                ('sp_atk', models.SmallIntegerField(db_column='Sp. Atk')),
                ('sp_def', models.SmallIntegerField(db_column='Sp. Def')),
                ('speed', models.SmallIntegerField(db_column='Speed')),
                ('generation', models.SmallIntegerField(db_column='Generation')),
                ('legendary', models.BooleanField(db_column='Legendary')),
            ],
            options={
                'db_table': 'pokemon',
                'managed': False,
            },
        ),
    ]
